name: example
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  cupertino_icons: ^1.0.5
  float_column: ^4.1.3
  flutter:
    sdk: flutter
  material_ui: ^1.1.0
  selectable:
    path: ../

dev_dependencies:
  flutter_lints_plus: ^3.2.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
